module.exports = class TwitterResult {
    id;
    observeeId;
    dateCreated;
    username;
    name;
    description;
    profilePictureUrl;
    bannerPictureUrl;
    profilePicturePhotoId;
    bannerPictureUrlId;
    location;
    followersCount;
    followingsCount;
    statussesCount;
    mediasCount;
    favoritesCount;
    protected;
    birthdayDay;
    birthdayMonth;
    birthdayYear;
}